### ISSUE TITLE
Could not compile cymunk module

### ISSUE THREAD

**Issue by stuaxo** [kivy/kivent#101]
Tried this on Ubuntu 64 bit 15.10 in a virtualenv - (the core module did work):

```
$ python setup.py install
missing cimport in module 'cymunk.cymunk': kivent_cymunk/interaction.pyx
missing cimport in module 'cymunk.cymunk': kivent_cymunk/interaction.pxd
missing cimport in module 'cymunk.cymunk': ./kivent_cymunk/physics.pxd
missing cimport in module 'cymunk.cymunk': kivent_cymunk/physics.pyx
missing cimport in module 'cymunk.cymunk': kivent_cymunk/physics.pxd
Compiling kivent_cymunk/interaction.pyx because it changed.
Compiling kivent_cymunk/physics.pyx because it changed.
[1/2] Cythonizing kivent_cymunk/interaction.pyx

Error compiling Cython file:
------------------------------------------------------------
...
from cymunk.cymunk cimport (Body, PivotJoint, GearJoint, cpBody, cpPivotJoint)
^
------------------------------------------------------------

kivent_cymunk/interaction.pxd:1:0: 'cymunk/cymunk.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from cymunk.cymunk cimport (Body, PivotJoint, GearJoint, cpBody, cpPivotJoint)
^
------------------------------------------------------------

kivent_cymunk/interaction.pxd:1:0: 'cymunk/cymunk/Body.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from cymunk.cymunk cimport (Body, PivotJoint, GearJoint, cpBody, cpPivotJoint)
^
------------------------------------------------------------

kivent_cymunk/interaction.pxd:1:0: 'cymunk/cymunk/PivotJoint.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from cymunk.cymunk cimport (Body, PivotJoint, GearJoint, cpBody, cpPivotJoint)
^
------------------------------------------------------------

kivent_cymunk/interaction.pxd:1:0: 'cymunk/cymunk/GearJoint.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from cymunk.cymunk cimport (Body, PivotJoint, GearJoint, cpBody, cpPivotJoint)
^
------------------------------------------------------------

kivent_cymunk/interaction.pxd:1:0: 'cymunk/cymunk/cpBody.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from cymunk.cymunk cimport (Body, PivotJoint, GearJoint, cpBody, cpPivotJoint)
^
------------------------------------------------------------

kivent_cymunk/interaction.pxd:1:0: 'cymunk/cymunk/cpPivotJoint.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from kivent_core.systems.staticmemgamesystem cimport (StaticMemGameSystem, 
    MemComponent)

ctypedef struct CymunkTouchStruct:
    unsigned int entity_id
    cpBody* touch_body 
   ^
------------------------------------------------------------

kivent_cymunk/interaction.pxd:8:4: 'cpBody' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
    MemComponent)

ctypedef struct CymunkTouchStruct:
    unsigned int entity_id
    cpBody* touch_body 
    cpPivotJoint* pivot
   ^
------------------------------------------------------------

kivent_cymunk/interaction.pxd:9:4: 'cpPivotJoint' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
    unsigned int entity_id
    cpBody* touch_body 
    cpPivotJoint* pivot

cdef class CymunkTouchComponent(MemComponent):
    cdef Body _touch_body
        ^
------------------------------------------------------------

kivent_cymunk/interaction.pxd:12:9: 'Body' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
    cpBody* touch_body 
    cpPivotJoint* pivot

cdef class CymunkTouchComponent(MemComponent):
    cdef Body _touch_body
    cdef PivotJoint _pivot
        ^
------------------------------------------------------------

kivent_cymunk/interaction.pxd:13:9: 'PivotJoint' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...

cdef class CymunkTouchSystem(StaticMemGameSystem):
    pass

cdef class SteeringComponent: 
    cdef Body _steering_body
        ^
------------------------------------------------------------

kivent_cymunk/interaction.pxd:19:9: 'Body' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
cdef class CymunkTouchSystem(StaticMemGameSystem):
    pass

cdef class SteeringComponent: 
    cdef Body _steering_body
    cdef PivotJoint _pivot
        ^
------------------------------------------------------------

kivent_cymunk/interaction.pxd:20:9: 'PivotJoint' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
    pass

cdef class SteeringComponent: 
    cdef Body _steering_body
    cdef PivotJoint _pivot
    cdef GearJoint _gear
        ^
------------------------------------------------------------

kivent_cymunk/interaction.pxd:21:9: 'GearJoint' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
# cython: profile=True
# cython: embedsignature=True
from cymunk.cymunk cimport (GearJoint, PivotJoint, Vec2d, cpVect, cpv,
^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:3:0: 'cymunk/cymunk/Vec2d.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
# cython: profile=True
# cython: embedsignature=True
from cymunk.cymunk cimport (GearJoint, PivotJoint, Vec2d, cpVect, cpv,
^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:3:0: 'cymunk/cymunk/cpVect.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
# cython: profile=True
# cython: embedsignature=True
from cymunk.cymunk cimport (GearJoint, PivotJoint, Vec2d, cpVect, cpv,
^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:3:0: 'cymunk/cymunk/cpv.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
# cython: profile=True
# cython: embedsignature=True
from cymunk.cymunk cimport (GearJoint, PivotJoint, Vec2d, cpVect, cpv,
^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:3:0: 'cymunk/cymunk/cpFloat.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
# cython: profile=True
# cython: embedsignature=True
from cymunk.cymunk cimport (GearJoint, PivotJoint, Vec2d, cpVect, cpv,
^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:3:0: 'cymunk/cymunk/cpBool.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
# cython: profile=True
# cython: embedsignature=True
from cymunk.cymunk cimport (GearJoint, PivotJoint, Vec2d, cpVect, cpv,
^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:3:0: 'cymunk/cymunk/cpvunrotate.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
# cython: profile=True
# cython: embedsignature=True
from cymunk.cymunk cimport (GearJoint, PivotJoint, Vec2d, cpVect, cpv,
^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:3:0: 'cymunk/cymunk/cpvrotate.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
# cython: profile=True
# cython: embedsignature=True
from cymunk.cymunk cimport (GearJoint, PivotJoint, Vec2d, cpVect, cpv,
^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:3:0: 'cymunk/cymunk/cpvdot.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
# cython: profile=True
# cython: embedsignature=True
from cymunk.cymunk cimport (GearJoint, PivotJoint, Vec2d, cpVect, cpv,
^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:3:0: 'cymunk/cymunk/cpvsub.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
# cython: profile=True
# cython: embedsignature=True
from cymunk.cymunk cimport (GearJoint, PivotJoint, Vec2d, cpVect, cpv,
^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:3:0: 'cymunk/cymunk/cpvnear.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
# cython: profile=True
# cython: embedsignature=True
from cymunk.cymunk cimport (GearJoint, PivotJoint, Vec2d, cpVect, cpv,
^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:3:0: 'cymunk/cymunk/cpvmult.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
# cython: profile=True
# cython: embedsignature=True
from cymunk.cymunk cimport (GearJoint, PivotJoint, Vec2d, cpVect, cpv,
^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:3:0: 'cymunk/cymunk/cpvlerp.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
# cython: profile=True
# cython: embedsignature=True
from cymunk.cymunk cimport (GearJoint, PivotJoint, Vec2d, cpVect, cpv,
^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:3:0: 'cymunk/cymunk/Space.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from kivent_core.systems.staticmemgamesystem cimport (StaticMemGameSystem, 
    MemComponent)


cdef class PhysicsComponent(MemComponent):
    cdef Body _body
        ^
------------------------------------------------------------

kivent_cymunk/physics.pxd:7:9: 'Body' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
    cdef list _shapes
    cdef str _shape_type

ctypedef struct PhysicsStruct:
    unsigned int entity_id
    cpBody* body
   ^
------------------------------------------------------------

kivent_cymunk/physics.pxd:13:4: 'cpBody' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
    unsigned int entity_id
    cpBody* body


cdef class CymunkPhysics(StaticMemGameSystem):
    cdef Space space
        ^
------------------------------------------------------------

kivent_cymunk/physics.pxd:17:9: 'Space' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
    cdef list bb_query_result
    cdef list on_screen_result
    cdef list segment_query_result

    cdef unsigned int _init_component(self, unsigned int component_index, 
        unsigned int entity_id, cpBody* body, str zone_name) except -1
                               ^
------------------------------------------------------------

kivent_cymunk/physics.pxd:23:32: 'cpBody' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
            self._pivot.error_bias = error_bias

    property touch_body:
        def __get__(self):
            return self._touch_body
        def __set__(self, Body body):
                         ^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:74:26: 'Body' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
            self._touch_body = body

    property pivot:
        def __get__(self):
            return self._pivot
        def __set__(self, PivotJoint pivot):
                         ^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:80:26: 'PivotJoint' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
            body.p = new_point


cdef class SteeringComponent: 

    def __cinit__(self, Body body, PivotJoint pivot, GearJoint gear,
                       ^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:362:24: 'Body' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
            body.p = new_point


cdef class SteeringComponent: 

    def __cinit__(self, Body body, PivotJoint pivot, GearJoint gear,
                                  ^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:362:35: 'PivotJoint' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
            body.p = new_point


cdef class SteeringComponent: 

    def __cinit__(self, Body body, PivotJoint pivot, GearJoint gear,
                                                    ^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:362:53: 'GearJoint' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        self._active = True

    property steering_body:
        def __get__(self):
            return self._steering_body
        def __set__(self, Body body):
                         ^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:374:26: 'Body' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
            self._steering_body = body

    property pivot:
        def __get__(self):
            return self._pivot
        def __set__(self, PivotJoint pivot):
                         ^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:380:26: 'PivotJoint' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
            self._pivot = pivot

    property gear:
        def __get__(self):
            return self._gear
        def __set__(self, GearJoint gear):
                         ^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:386:26: 'GearJoint' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        component.entity_id = entity_id
        gameworld = self.gameworld
        cdef SystemManager system_manager = gameworld.system_manager
        cdef str physics_id = self.physics_system
        cdef object physics_system = system_manager[physics_id]
        cdef Body touch_body = Body(None, None)
            ^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:188:13: 'Body' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        cdef tuple touch_pos = args['touch_pos']
        cdef unsigned int touched_ent = args['touched_ent']
        touched_entity = entities[touched_ent]
        cdef PhysicsComponent physics_data = getattr(
            touched_entity, physics_id)
        cdef Body body = physics_data.body
            ^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:195:13: 'Body' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        cdef unsigned int touched_ent = args['touched_ent']
        touched_entity = entities[touched_ent]
        cdef PhysicsComponent physics_data = getattr(
            touched_entity, physics_id)
        cdef Body body = physics_data.body
        cdef cpVect body_local = body.world_to_local(touch_pos)
            ^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:196:13: 'cpVect' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        cdef PhysicsComponent physics_data = getattr(
            touched_entity, physics_id)
        cdef Body body = physics_data.body
        cdef cpVect body_local = body.world_to_local(touch_pos)
        cdef tuple body_pos = (body_local.x, body_local.y)
        cdef PivotJoint pivot = PivotJoint(touch_body, body, (0., 0.), 
            ^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:198:13: 'PivotJoint' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
            body_pos)
        touch_body._body.p = cpv(touch_pos[0], touch_pos[1])
        pivot.max_bias = args['max_bias']
        pivot.error_bias = cpow(1.0 - 0.15, 60.0)
        pivot.max_force = args['max_force']
        cdef Space space = physics_system.space
            ^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:204:13: 'Space' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        self.entity_components.remove_entity(component.entity_id)
        gameworld = self.gameworld
        cdef str physics_id = self.physics_system
        cdef SystemManager system_manager = gameworld.system_manager
        physics_system = system_manager[physics_id]
        cdef Space space = physics_system.space
            ^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:252:13: 'Space' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...

    def update(self, float dt):
        gameworld = self.gameworld
        cdef CymunkTouchStruct* system_component 
        cdef PositionStruct2D* pos_comp
        cdef cpBody* body
            ^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:335:13: 'cpBody' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
    def update(self, float dt):
        gameworld = self.gameworld
        cdef CymunkTouchStruct* system_component 
        cdef PositionStruct2D* pos_comp
        cdef cpBody* body
        cdef cpVect p_position
            ^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:336:13: 'cpVect' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        gameworld = self.gameworld
        cdef CymunkTouchStruct* system_component 
        cdef PositionStruct2D* pos_comp
        cdef cpBody* body
        cdef cpVect p_position
        cdef cpVect body_pos
            ^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:337:13: 'cpVect' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        cdef CymunkTouchStruct* system_component 
        cdef PositionStruct2D* pos_comp
        cdef cpBody* body
        cdef cpVect p_position
        cdef cpVect body_pos
        cdef cpVect new_vel
            ^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:338:13: 'cpVect' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
        cdef PositionStruct2D* pos_comp
        cdef cpBody* body
        cdef cpVect p_position
        cdef cpVect body_pos
        cdef cpVect new_vel
        cdef cpVect new_point
            ^
------------------------------------------------------------

kivent_cymunk/interaction.pyx:339:13: 'cpVect' is not a type identifier
Traceback (most recent call last):
  File "setup.py", line 71, in <module>
    cymunk_extensions, cymunk_modules)
  File "setup.py", line 54, in build_extensions_for_modules_cython
    return cythonize(ext_list)
  File "/mnt/data/home/stu/.virtualenvs/3d/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 877, in cythonize
    cythonize_one(*args)
  File "/mnt/data/home/stu/.virtualenvs/3d/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 997, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: kivent_cymunk/interaction.pyx
 3d  stu  beezlebub  ~  projects  …  kivent  modules  cymun
```

**Comment by Kovak** [comment]
You must have cymunk built and in your python env or installed into the python.

**Comment by stuaxo** [comment]
Cheers :)
