### ISSUE TITLE
installing kivent within portable kivy

### ISSUE THREAD

**Issue by gantlion** [kivy/kivent#102]
Installation fails when following the installation steps for the portable kivy:

cd KivEnt/modules/core
python setup.py build_ext install

fails with:
[INFO              ] [Logger      ] Record log in C:\Users\gantl\.kivy\logs\kivy_15-11-14_22.txt
[INFO              ] [Kivy        ] v1.9.0
[INFO              ] [Python      ] v3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)]
 Traceback (most recent call last):
   File "setup.py", line 104, in <module>
     extensions, core_modules)
   File "setup.py", line 82, in build_extensions_for_modules_cython
     include_dirs=kivy.get_includes())
 AttributeError: 'module' object has no attribute 'get_includes'

**Comment by gantlion** [comment]
Fixed it by installing it into the latest development version of kivy from github
