### ISSUE TITLE
Tilemap Example

### ISSUE THREAD

**Issue by jpartain** [kivy/kivent#175]
I'm trying to check KivEnt maps out, but the example 13_tilemap isn't running for me on branch 2.2-dev. I've compiled/installed Kivy 1.9.2-dev0, Cython 0.23. It seems like the arguments to .load_map() are incorrect, but when I correct them (like unpacking the tuple there to two single arguments) I get a MemoryError. My traceback is:

 Traceback (most recent call last):
   File "main.py", line 103, in <module>
     YourAppNameApp().run()
   File "/usr/local/lib/python3.5/dist-packages/kivy/app.py", line 828, in run
     runTouchApp()
   File "/usr/local/lib/python3.5/dist-packages/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/local/lib/python3.5/dist-packages/kivy/core/window/window_pygame.py", line 402, in mainloop
     self._mainloop()
   File "/usr/local/lib/python3.5/dist-packages/kivy/core/window/window_pygame.py", line 289, in _mainloop
     EventLoop.idle()
   File "/usr/local/lib/python3.5/dist-packages/kivy/base.py", line 327, in idle
     Clock.tick()
   File "/usr/local/lib/python3.5/dist-packages/kivy/clock.py", line 581, in tick
     self._process_events()
   File "kivy/_clock.pyx", line 368, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:7731)
   File "kivy/_clock.pyx", line 398, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:7608)
   File "kivy/_clock.pyx", line 396, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:7529)
   File "kivy/_clock.pyx", line 168, in kivy._clock.ClockEvent.tick (kivy/_clock.c:3514)
   File "kivent_core/gameworld.pyx", line 282, in kivent_core.gameworld.GameWorld.init_gameworld.lambda (kivent_core/gameworld.c:6577)
   File "kivent_core/gameworld.pyx", line 279, in kivent_core.gameworld.GameWorld.init_gameworld (kivent_core/gameworld.c:6826)
   File "main.py", line 30, in init_game
     self.setup_tile_map()
   File "main.py", line 86, in setup_tile_map
     map_manager.load_map('my_map', (100, 100), 64, tiles)
   File "kivent_maps/map_manager.pyx", line 46, in kivent_maps.map_manager.MapManager.load_map (kivent_maps/map_manager.c:2032)
 TypeError: an integer is required

**Comment by udiboy1209** [comment]
I haven't updated this example after adding multilayer support to the maps module. That is what is giving the error. I will fix this example in a few days. 

Till then you can try out the 14th example for a demo of how to use TMX maps in kivent.
