### ISSUE TITLE
Installing kivent 2.2, maps module: 'VertexFormat2F4UB' is not a type identifier

### ISSUE THREAD

**Issue by spinningD20** [kivy/kivent#177]
After installing kivent_core and all other modules, maps module complains:

```
[INFO   ] [Logger      ] Record log in /root/.kivy/logs/kivy_16-12-11_14.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.12 (default, Nov  7 2016, 11:55:55) 
[GCC 6.2.1 20160830]
Compiling kivent_maps/map_data.pyx because it changed.
Compiling kivent_maps/map_system.pyx because it changed.
Compiling kivent_maps/map_manager.pyx because it changed.
[1/3] Cythonizing kivent_maps/map_data.pyx

Error compiling Cython file:

...
from kivent_core.rendering.model cimport VertexModel
from kivent_core.rendering.vertex_formats cimport VertexFormat2F4UB
^


kivent_maps/map_data.pyx:2:0: 'kivent_core/rendering/vertex_formats/VertexFormat2F4UB.pxd' not found

Error compiling Cython file:

...
             return self.layer

property color:
    def __get__(self):
        cdef VertexModel model = <VertexModel>self.obj_pointer.model
        cdef VertexFormat2F4UB* vertex = \
            ^


kivent_maps/map_data.pyx:200:17: 'VertexFormat2F4UB' is not a type identifier

Error compiling Cython file:

...

property color:
    def __get__(self):
        cdef VertexModel model = <VertexModel>self.obj_pointer.model
        cdef VertexFormat2F4UB* vertex = \
                <VertexFormat2F4UB*>model.vertices_block.data
                ^


kivent_maps/map_data.pyx:201:21: 'VertexFormat2F4UB' is not a type identifier
Traceback (most recent call last):
   File "setup.py", line 80, in <module>
     particles_extensions, particles_modules)
   File "setup.py", line 62, in build_extensions_for_modules_cython
     return cythonize(ext_list)
   File "/usr/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 915, in cythonize
     cythonize_one(*args)
   File "/usr/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1037, in cythonize_one
     raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: kivent_maps/map_data.pyx

```

I looked where it's supposedly referenced (core/kivent_core/rendering/vertex_formats.pxd) and it looks like there's a struct for it, and I found site-packages/kivent_core/rendering/vertex_formats.pxd and .so.

This is on Arch linux, relatively fresh install, after installing kivy 192dev0, cython, and cloning kivent 2.2 dev.  Tested and ran into issue on both python2 and python3, everything else related to kivent seems to install.

Thanks!

**Comment by udiboy1209** [comment]
The actual error is `'kivent_core/rendering/vertex_formats/VertexFormat2F4UB.pxd' not found`. It should import `VertexFormat2F4UB` from `vertex_formats.pxd`, and obviously there shouldn't be a `VertexFormat2F4UB.pxd`. What cython version have you installed, might be a problem with that. I have tested everything with 0.23 .

**Comment by spinningD20** [comment]
That was it, cython was .24 in python2 and .25 in python3.  My bad!  kivent_core compiled weird because of that.
