### ISSUE TITLE
Error running tmx example - 'Color' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by spinningD20** [kivy/kivent#178]
```
/home/mike/pydev/bin/python2 /home/mike/Downloads/kivent-2.2-dev/examples/14_tmx_loader/main.py
[INFO   ] [Logger      ] Record log in /home/mike/.kivy/logs/kivy_16-12-14_118.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.12 (default, Nov  7 2016, 11:55:55) 
[GCC 6.2.1 20160830]
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 13.0.1>
[INFO   ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO   ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) Haswell Mobile >
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [AudioGstplayer] Using Gstreamer 1.10.2.0
[INFO   ] [Audio       ] Providers: audio_gstplayer, audio_sdl2 (audio_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Shader      ] Read </home/mike/Downloads/kivent-2.2-dev/examples/assets/glsl/positionshader.glsl>
[INFO   ] [Shader      ] Read <poscolorshader.glsl>
[INFO   ] [Shader      ] Read </home/mike/Downloads/kivent-2.2-dev/examples/assets/glsl/positionshader.glsl>
[INFO   ] [Shader      ] Read <poscolorshader.glsl>
[INFO   ] [Shader      ] Read </home/mike/Downloads/kivent-2.2-dev/examples/assets/glsl/positionshader.glsl>
[INFO   ] [Shader      ] Read <poscolorshader.glsl>
[INFO   ] [Shader      ] Read </home/mike/Downloads/kivent-2.2-dev/examples/assets/glsl/positionshader.glsl>
[INFO   ] [Shader      ] Read <poscolorshader.glsl>
[ERROR  ] [GameSystem  ] System_id: position not attached retrying in 1 sec. If you see this error once or twice, we are probably just waiting on the KV file to load. If you see it a whole bunch something is probably wrong. Make sure all systems are setup properly.
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [KivEnt      ] Vertex Format: vertex_format_4f registered. Size per vertex is: 16. Format is [('pos', 2, 'float', 0, False), ('uvs', 2, 'float', 8, False)].
[INFO   ] [KivEnt      ] Vertex Format: vertex_format_2f4ub registered. Size per vertex is: 12. Format is [('pos', 2, 'float', 0, False), ('v_color', 4, 'ubyte', 8, True)].
[INFO   ] [KivEnt      ] Vertex Format: vertex_format_7f registered. Size per vertex is: 28. Format is [('pos', 2, 'float', 0, False), ('uvs', 2, 'float', 8, False), ('rot', 1, 'float', 16, False), ('center', 2, 'float', 20, False)].
[INFO   ] [KivEnt      ] Vertex Format: vertex_format_7f4ub registered. Size per vertex is: 32. Format is [('pos', 2, 'float', 0, False), ('uvs', 2, 'float', 8, False), ('rot', 1, 'float', 16, False), ('center', 2, 'float', 20, False), ('v_color', 4, 'ubyte', 28, True)].
[INFO   ] [KivEnt      ] Vertex Format: vertex_format_4f4ub registered. Size per vertex is: 20. Format is [('pos', 2, 'float', 0, False), ('uvs', 2, 'float', 8, False), ('v_color', 4, 'ubyte', 16, True)].
[INFO   ] [KivEnt      ] Model Manager reserved space for vertex format: vertex_format_4f. 75 KiB was reserved for vertices, fitting a total of 4800. 25 KiB was reserved for indices fitting a total of 12800.
[INFO   ] [KivEnt      ] Model Manager reserved space for vertex format: vertex_format_2f4ub. 75 KiB was reserved for vertices, fitting a total of 6400. 25 KiB was reserved for indices fitting a total of 12800.
[INFO   ] [KivEnt      ] Model Manager reserved space for vertex format: vertex_format_7f. 75 KiB was reserved for vertices, fitting a total of 2742. 25 KiB was reserved for indices fitting a total of 12800.
[INFO   ] [KivEnt      ] Model Manager reserved space for vertex format: vertex_format_7f4ub. 75 KiB was reserved for vertices, fitting a total of 2400. 25 KiB was reserved for indices fitting a total of 12800.
[INFO   ] [KivEnt      ] Model Manager reserved space for vertex format: vertex_format_4f4ub. 75 KiB was reserved for vertices, fitting a total of 3840. 25 KiB was reserved for indices fitting a total of 12800.
[INFO   ] [KivEnt      ] Batches for canvas: <kivy.graphics.instructions.RenderContext object at 0x7fd62d0c2a10> will have 21845 verts and 131072 indices.VBO will be 256 in KiB per frame with 40 total vbos, an estimated 5461 enities fit in each batch with 4 verts per entity
[INFO   ] [KivEnt      ] map_layer3_polygons allocated 27748 KiB
[INFO   ] [KivEnt      ] map_layer1_animator allocated 4690 KiB
[INFO   ] [KivEnt      ] Batches for canvas: <kivy.graphics.instructions.RenderContext object at 0x7fd62cf2df50> will have 21845 verts and 131072 indices.VBO will be 256 in KiB per frame with 40 total vbos, an estimated 5461 enities fit in each batch with 4 verts per entity
[INFO   ] [KivEnt      ] map_layer1_polygons allocated 27748 KiB
[INFO   ] [KivEnt      ] Batches for canvas: <kivy.graphics.instructions.RenderContext object at 0x7fd62d0c24d0> will have 21845 verts and 131072 indices.VBO will be 256 in KiB per frame with 40 total vbos, an estimated 5461 enities fit in each batch with 4 verts per entity
[INFO   ] [KivEnt      ] map_layer2_polygons allocated 27748 KiB
[INFO   ] [KivEnt      ] color allocated 784 KiB
[INFO   ] [KivEnt      ] Batches for canvas: <kivy.graphics.instructions.RenderContext object at 0x7fd62cf2da10> will have 21845 verts and 131072 indices.VBO will be 256 in KiB per frame with 40 total vbos, an estimated 5461 enities fit in each batch with 4 verts per entity
[INFO   ] [KivEnt      ] map_layer0_polygons allocated 27748 KiB
[INFO   ] [KivEnt      ] Batches for canvas: <kivy.graphics.instructions.RenderContext object at 0x7fd62d0c2950> will have 16384 verts and 131072 indices.VBO will be 256 in KiB per frame with 40 total vbos, an estimated 4096 enities fit in each batch with 4 verts per entity
[INFO   ] [KivEnt      ] map_layer3 allocated 26488 KiB
[INFO   ] [KivEnt      ] map_layer3_animator allocated 4690 KiB
[INFO   ] [KivEnt      ] tile_map allocated 3918 KiB
[INFO   ] [KivEnt      ] position allocated 1176 KiB
[INFO   ] [KivEnt      ] map_layer0_animator allocated 4690 KiB
[INFO   ] [KivEnt      ] Batches for canvas: <kivy.graphics.instructions.RenderContext object at 0x7fd62d0c2410> will have 16384 verts and 131072 indices.VBO will be 256 in KiB per frame with 40 total vbos, an estimated 4096 enities fit in each batch with 4 verts per entity
[INFO   ] [KivEnt      ] map_layer2 allocated 26488 KiB
[INFO   ] [KivEnt      ] map_layer2_animator allocated 4690 KiB
[INFO   ] [KivEnt      ] Batches for canvas: <kivy.graphics.instructions.RenderContext object at 0x7fd62cf2d950> will have 16384 verts and 131072 indices.VBO will be 256 in KiB per frame with 40 total vbos, an estimated 4096 enities fit in each batch with 4 verts per entity
[INFO   ] [KivEnt      ] map_layer0 allocated 26488 KiB
[INFO   ] [KivEnt      ] Batches for canvas: <kivy.graphics.instructions.RenderContext object at 0x7fd62cf2de90> will have 16384 verts and 131072 indices.VBO will be 256 in KiB per frame with 40 total vbos, an estimated 4096 enities fit in each batch with 4 verts per entity
[INFO   ] [KivEnt      ] map_layer1 allocated 26488 KiB
[INFO   ] [KivEnt      ] We will need 249266 KiB for game, we have 256000 KiB
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "/home/mike/Downloads/kivent-2.2-dev/examples/14_tmx_loader/main.py", line 102, in <module>
     YourAppNameApp().run()
   File "/home/mike/pydev/lib/python2.7/site-packages/kivy/app.py", line 828, in run
     runTouchApp()
   File "/home/mike/pydev/lib/python2.7/site-packages/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/home/mike/pydev/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 637, in mainloop
     self._mainloop()
   File "/home/mike/pydev/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 390, in _mainloop
     EventLoop.idle()
   File "/home/mike/pydev/lib/python2.7/site-packages/kivy/base.py", line 327, in idle
     Clock.tick()
   File "/home/mike/pydev/lib/python2.7/site-packages/kivy/clock.py", line 581, in tick
     self._process_events()
   File "kivy/_clock.pyx", line 368, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:7392)
   File "kivy/_clock.pyx", line 398, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:7269)
   File "kivy/_clock.pyx", line 396, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:7190)
   File "kivy/_clock.pyx", line 168, in kivy._clock.ClockEvent.tick (kivy/_clock.c:3290)
   File "kivent_core/gameworld.pyx", line 282, in kivent_core.gameworld.GameWorld.init_gameworld.lambda (kivent_core/gameworld.c:5906)
   File "kivent_core/gameworld.pyx", line 279, in kivent_core.gameworld.GameWorld.init_gameworld (kivent_core/gameworld.c:6116)
   File "/home/mike/Downloads/kivent-2.2-dev/examples/14_tmx_loader/main.py", line 59, in init_game
     self.setup_tile_map()
   File "/home/mike/Downloads/kivent-2.2-dev/examples/14_tmx_loader/main.py", line 69, in setup_tile_map
     map_name = map_utils.parse_tmx(filename, self.gameworld)
   File "/home/mike/pydev/lib/python2.7/site-packages/kivent_maps/map_utils.py", line 181, in parse_tmx
     _load_tile_properties(tilemap.tilesets))
   File "/home/mike/pydev/lib/python2.7/site-packages/kivent_maps/map_utils.py", line 360, in _load_tile_map
     color = get_color_from_hex(layer.color)
   File "/home/mike/pydev/lib/python2.7/site-packages/kivy/utils.py", line 116, in get_color_from_hex
     if s.startswith('#'):
 AttributeError: 'Color' object has no attribute 'startswith'
```

I'm not familiar enough with doing a PR, but I fixed this by changing this line in map_utils.py, line 360:

color = get_color_from_hex(layer.color)

to

color = get_color_from_hex(layer.color.hex_string)

At least it displays, etc, so I assume that's what you wanted instead - if not let me know, and if I can improve my contributions, I'm still learning.  Thanks!

**Comment by udiboy1209** [comment]
Are you using the same map as in the example?

**Comment by spinningD20** [comment]
Yep, just running main.py, no modifications.

**Comment by udiboy1209** [comment]
@spinningD20 I'd advise you downgrade `tmx` to `1.8.1`. The `1.9` version is throwing errors with the new color change.
