### ISSUE TITLE
using rotate_renderer, ends up with error (kivent_core/memory_handlers/pool.c:1464)

### ISSUE THREAD

**Issue by thegameguy** [kivy/kivent#219]
Traceback (most recent call last):
   File "D:\kivent\kivent-master\examples\adding_physics_objects\main.py", line 138, in <module>
     YourAppNameApp().run()
   File "C:\Python27\lib\site-packages\kivy\app.py", line 828, in run
     runTouchApp()
   File "C:\Python27\lib\site-packages\kivy\base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 663, in mainloop
     self._mainloop()
   File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 405, in _mainloop
     EventLoop.idle()
   File "C:\Python27\lib\site-packages\kivy\base.py", line 339, in idle
     Clock.tick()
   File "C:\Python27\lib\site-packages\kivy\clock.py", line 581, in tick
     self._process_events()
   File "kivy\_clock.pyx", line 367, in kivy._clock.CyClockBase._process_events (c:\users\metal\appdata\local\temp\pip-hqvxgh-build\kivy\_clock.c:7410)
   File "kivy\_clock.pyx", line 397, in kivy._clock.CyClockBase._process_events (c:\users\metal\appdata\local\temp\pip-hqvxgh-build\kivy\_clock.c:7285)
   File "kivy\_clock.pyx", line 395, in kivy._clock.CyClockBase._process_events (c:\users\metal\appdata\local\temp\pip-hqvxgh-build\kivy\_clock.c:7207)
   File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick (c:\users\metal\appdata\local\temp\pip-hqvxgh-build\kivy\_clock.c:3201)
   File "kivent_core\gameworld.pyx", line 282, in kivent_core.gameworld.GameWorld.init_gameworld.lambda (kivent_core/gameworld.c:5909)
   File "kivent_core\gameworld.pyx", line 279, in kivent_core.gameworld.GameWorld.init_gameworld (kivent_core/gameworld.c:6119)
   File "D:\kivent\kivent-master\examples\adding_physics_objects\main.py", line 54, in init_game
     self.draw_some_stuff()
   File "D:\kivent\kivent-master\examples\adding_physics_objects\main.py", line 66, in draw_some_stuff
     ent_id = create_asteroid(pos)
   File "D:\kivent\kivent-master\examples\adding_physics_objects\main.py", line 105, in create_asteroid
     ent = init_entity(create_component_dict, component_order)
   File "kivent_core\gameworld.pyx", line 441, in kivent_core.gameworld.GameWorld.init_entity (kivent_core/gameworld.c:8226)
   File "kivent_core\systems\gamesystem.pyx", line 260, in kivent_core.systems.gamesystem.GameSystem.create_component (kivent_core/systems/gamesystem.c:3726)
   File "kivent_core\systems\renderers.pyx", line 529, in kivent_core.systems.renderers.Renderer.init_component (kivent_core/systems/renderers.c:11559)
   File "kivent_core\systems\renderers.pyx", line 468, in kivent_core.systems.renderers.Renderer._init_component (kivent_core/systems/renderers.c:10759)
   File "kivent_core\systems\renderers.pyx", line 696, in kivent_core.systems.renderers.Renderer._batch_entity (kivent_core/systems/renderers.c:13018)
   File "kivent_core\rendering\batching.pyx", line 564, in kivent_core.rendering.batching.BatchManager.batch_entity (kivent_core/rendering/batching.c:8740)
   File "kivent_core\rendering\batching.pyx", line 94, in kivent_core.rendering.batching.IndexedBatch.add_entity (kivent_core/rendering/batching.c:5171)
   File "kivent_core\systems\staticmemgamesystem.pyx", line 574, in kivent_core.systems.staticmemgamesystem.ComponentPointerAggregator.add_entity (kivent_core/systems/staticmemgamesystem.c:5224)
   File "kivent_core\memory_handlers\zone.pyx", line 298, in kivent_core.memory_handlers.zone.MemoryZone.get_pointer (kivent_core/memory_handlers/zone.c:2785)
   File "kivent_core\memory_handlers\pool.pyx", line 153, in kivent_core.memory_handlers.pool.MemoryPool.get_pointer (kivent_core/memory_handlers/pool.c:1554)
   File "kivent_core\memory_handlers\pool.pyx", line 131, in kivent_core.memory_handlers.pool.MemoryPool.get_memory_block_from_index (kivent_core/memory_handlers/pool.c:1464)
 IndexError: list index out of range

**Comment by SleepProgger** [comment]
Did you change anything in that example ?
Because the original `adding_physics_objects` example code runs without a problem for me.

**Comment by Kovak** [comment]
I think this one was debugged on the mailing list going to close, please reopen if I'm wrong.
