### ISSUE TITLE
Can't install Kivent_core.

### ISSUE THREAD

**Issue by DoAltPlusF4** [kivy/kivent#286]
When running `setup.py build_ext install` i get this error:
```Error compiling Cython file:
 ------------------------------------------------------------
 ...
 cdef class VertexInstruction
 cdef class CanvasBase
 cdef class Canvas
 cdef class RenderContext

 from vbo cimport *
 ^
 ------------------------------------------------------------
 
 E:\Projects\Arkius\.env\lib\site-packages\kivy\graphics\instructions.pxd:11:0: 'vbo.pxd' not found

 Error compiling Cython file:
 ------------------------------------------------------------
 ...
 cdef class CanvasBase
 cdef class Canvas
 cdef class RenderContext

 from vbo cimport *
 from compiler cimport *
 ^
 ------------------------------------------------------------

 E:\Projects\Arkius\.env\lib\site-packages\kivy\graphics\instructions.pxd:12:0: 'compiler.pxd' not found

 Error compiling Cython file:
 ------------------------------------------------------------
 ...
 cdef class Canvas
 cdef class RenderContext

 from vbo cimport *
 from compiler cimport *
 from shader cimport *
 ^
 ------------------------------------------------------------

 E:\Projects\Arkius\.env\lib\site-packages\kivy\graphics\instructions.pxd:13:0: 'shader.pxd' not found

 Error compiling Cython file:
 ------------------------------------------------------------
 ...
 cdef class RenderContext

 from vbo cimport *
 from compiler cimport *
 from shader cimport *
 from texture cimport Texture
 ^
 ------------------------------------------------------------

 E:\Projects\Arkius\.env\lib\site-packages\kivy\graphics\instructions.pxd:14:0: 'texture.pxd' not found
 
 Error compiling Cython file:
 ------------------------------------------------------------
 ...
 cdef class RenderContext

 from vbo cimport *
 from compiler cimport *
 from shader cimport *
 from texture cimport Texture
 ^
 ------------------------------------------------------------

 E:\Projects\Arkius\.env\lib\site-packages\kivy\graphics\instructions.pxd:14:0: 'texture\Texture.pxd' not found

 Error compiling Cython file:
 ------------------------------------------------------------
 ...
     cdef void rremove(self, InstructionGroup ig)

 cdef class InstructionGroup(Instruction):
     cdef public list children
     cdef InstructionGroup compiled_children
     cdef GraphicsCompiler compiler
         ^
 ------------------------------------------------------------

 E:\Projects\Arkius\.env\lib\site-packages\kivy\graphics\instructions.pxd:45:9: 'GraphicsCompiler' is not a type identifier

 Error compiling Cython file:
 ------------------------------------------------------------
 ...
     cdef int set_state(self, str name, value) except -1
     cdef int push_state(self, str name) except -1
     cdef int pop_state(self, str name) except -1


 from context_instructions cimport BindTexture
 ^
 ------------------------------------------------------------

 E:\Projects\Arkius\.env\lib\site-packages\kivy\graphics\instructions.pxd:66:0: 'context_instructions.pxd' not found

 Error compiling Cython file:
 ------------------------------------------------------------
 ...
     cdef int set_state(self, str name, value) except -1
     cdef int push_state(self, str name) except -1
     cdef int pop_state(self, str name) except -1


 from context_instructions cimport BindTexture
 ^
 ------------------------------------------------------------

 E:\Projects\Arkius\.env\lib\site-packages\kivy\graphics\instructions.pxd:66:0: 'context_instructions\BindTexture.pxd' not found

 Error compiling Cython file:
 ------------------------------------------------------------
 ...


 from context_instructions cimport BindTexture

 cdef class VertexInstruction(Instruction):
     cdef BindTexture texture_binding
         ^
 ------------------------------------------------------------

 E:\Projects\Arkius\.env\lib\site-packages\kivy\graphics\instructions.pxd:69:9: 'BindTexture' is not a type identifier

 Error compiling Cython file:
 ------------------------------------------------------------
 ...

 from context_instructions cimport BindTexture

 cdef class VertexInstruction(Instruction):
     cdef BindTexture texture_binding
     cdef VertexBatch batch
         ^
 ------------------------------------------------------------

 E:\Projects\Arkius\.env\lib\site-packages\kivy\graphics\instructions.pxd:70:9: 'VertexBatch' is not a type identifier

 Error compiling Cython file:
 ------------------------------------------------------------
 ...
     cdef void rremove(self, InstructionGroup ig)

     cdef void build(self)

 cdef class Callback(Instruction):
     cdef Shader _shader
         ^
 ------------------------------------------------------------

 E:\Projects\Arkius\.env\lib\site-packages\kivy\graphics\instructions.pxd:80:9: 'Shader' is not a type identifier
 
 Error compiling Cython file:
 ------------------------------------------------------------
 ...
     cpdef draw(self)
     cdef int apply(self) except -1


 cdef class RenderContext(Canvas):
     cdef Shader _shader
         ^
 ------------------------------------------------------------

 E:\Projects\Arkius\.env\lib\site-packages\kivy\graphics\instructions.pxd:106:9: 'Shader' is not a type identifier

 Error compiling Cython file:
 ------------------------------------------------------------
 ...
 

 cdef class RenderContext(Canvas):
     cdef Shader _shader
     cdef dict state_stacks
     cdef Texture default_texture
         ^
 ------------------------------------------------------------

 E:\Projects\Arkius\.env\lib\site-packages\kivy\graphics\instructions.pxd:108:9: 'Texture' is not a type identifier

 Error compiling Cython file:
 ------------------------------------------------------------
 ...
     cdef dict bind_texture
     cdef int _use_parent_projection
     cdef int _use_parent_modelview
     cdef int _use_parent_frag_modelview

     cdef void set_texture(self, int index, Texture texture)
                                           ^
 ------------------------------------------------------------

 E:\Projects\Arkius\.env\lib\site-packages\kivy\graphics\instructions.pxd:114:43: 'Texture' is not a type identifier
 Traceback (most recent call last):
   File "setup.py", line 184, in <module>
     extensions, core_modules)
   File "setup.py", line 164, in build_extensions_for_modules_cython
     return cythonize(ext_list, compiler_directives={'language_level': '3'})
   File "E:\Projects\Arkius\.env\lib\site-packages\Cython\Build\Dependencies.py", line 1096, in cythonize
     cythonize_one(*args)
   File "E:\Projects\Arkius\.env\lib\site-packages\Cython\Build\Dependencies.py", line 1219, in cythonize_one
     raise CompileError(None, pyx_file)
 Cython.Compiler.Errors.CompileError: kivent_core/managers/resource_managers.pyx```

**Comment by DoAltPlusF4** [comment]
Never mind, I'd forgot to install Cython.
New problem:
```Error compiling Cython file:
 ------------------------------------------------------------
 ...
 cdef class VertexInstruction
 cdef class CanvasBase
 cdef class Canvas
 cdef class RenderContext

 from vbo cimport *
 ^
 ------------------------------------------------------------
 
 E:\Projects\Arkius\.env\lib\site-packages\kivy\graphics\instructions.pxd:11:0: 'vbo.pxd' not found

 Error compiling Cython file:
 ------------------------------------------------------------
 ...
 cdef class CanvasBase
 cdef class Canvas
 cdef class RenderContext

 from vbo cimport *
 from compiler cimport *
 ^
 ------------------------------------------------------------

 E:\Projects\Arkius\.env\lib\site-packages\kivy\graphics\instructions.pxd:12:0: 'compiler.pxd' not found

 Error compiling Cython file:
 ------------------------------------------------------------
 ...
 cdef class Canvas
 cdef class RenderContext

 from vbo cimport *
 from compiler cimport *
 from shader cimport *
 ^
 ------------------------------------------------------------

 E:\Projects\Arkius\.env\lib\site-packages\kivy\graphics\instructions.pxd:13:0: 'shader.pxd' not found

 Error compiling Cython file:
 ------------------------------------------------------------
 ...
 cdef class RenderContext

 from vbo cimport *
 from compiler cimport *
 from shader cimport *
 from texture cimport Texture
 ^
 ------------------------------------------------------------

 E:\Projects\Arkius\.env\lib\site-packages\kivy\graphics\instructions.pxd:14:0: 'texture.pxd' not found
 
 Error compiling Cython file:
 ------------------------------------------------------------
 ...
 cdef class RenderContext

 from vbo cimport *
 from compiler cimport *
 from shader cimport *
 from texture cimport Texture
 ^
 ------------------------------------------------------------

 E:\Projects\Arkius\.env\lib\site-packages\kivy\graphics\instructions.pxd:14:0: 'texture\Texture.pxd' not found

 Error compiling Cython file:
 ------------------------------------------------------------
 ...
     cdef void rremove(self, InstructionGroup ig)

 cdef class InstructionGroup(Instruction):
     cdef public list children
     cdef InstructionGroup compiled_children
     cdef GraphicsCompiler compiler
         ^
 ------------------------------------------------------------

 E:\Projects\Arkius\.env\lib\site-packages\kivy\graphics\instructions.pxd:45:9: 'GraphicsCompiler' is not a type identifier

 Error compiling Cython file:
 ------------------------------------------------------------
 ...
     cdef int set_state(self, str name, value) except -1
     cdef int push_state(self, str name) except -1
     cdef int pop_state(self, str name) except -1


 from context_instructions cimport BindTexture
 ^
 ------------------------------------------------------------

 E:\Projects\Arkius\.env\lib\site-packages\kivy\graphics\instructions.pxd:66:0: 'context_instructions.pxd' not found

 Error compiling Cython file:
 ------------------------------------------------------------
 ...
     cdef int set_state(self, str name, value) except -1
     cdef int push_state(self, str name) except -1
     cdef int pop_state(self, str name) except -1


 from context_instructions cimport BindTexture
 ^
 ------------------------------------------------------------

 E:\Projects\Arkius\.env\lib\site-packages\kivy\graphics\instructions.pxd:66:0: 'context_instructions\BindTexture.pxd' not found

 Error compiling Cython file:
 ------------------------------------------------------------
 ...


 from context_instructions cimport BindTexture

 cdef class VertexInstruction(Instruction):
     cdef BindTexture texture_binding
         ^
 ------------------------------------------------------------

 E:\Projects\Arkius\.env\lib\site-packages\kivy\graphics\instructions.pxd:69:9: 'BindTexture' is not a type identifier

 Error compiling Cython file:
 ------------------------------------------------------------
 ...

 from context_instructions cimport BindTexture

 cdef class VertexInstruction(Instruction):
     cdef BindTexture texture_binding
     cdef VertexBatch batch
         ^
 ------------------------------------------------------------

 E:\Projects\Arkius\.env\lib\site-packages\kivy\graphics\instructions.pxd:70:9: 'VertexBatch' is not a type identifier

 Error compiling Cython file:
 ------------------------------------------------------------
 ...
     cdef void rremove(self, InstructionGroup ig)

     cdef void build(self)

 cdef class Callback(Instruction):
     cdef Shader _shader
         ^
 ------------------------------------------------------------

 E:\Projects\Arkius\.env\lib\site-packages\kivy\graphics\instructions.pxd:80:9: 'Shader' is not a type identifier
 
 Error compiling Cython file:
 ------------------------------------------------------------
 ...
     cpdef draw(self)
     cdef int apply(self) except -1


 cdef class RenderContext(Canvas):
     cdef Shader _shader
         ^
 ------------------------------------------------------------

 E:\Projects\Arkius\.env\lib\site-packages\kivy\graphics\instructions.pxd:106:9: 'Shader' is not a type identifier

 Error compiling Cython file:
 ------------------------------------------------------------
 ...
 

 cdef class RenderContext(Canvas):
     cdef Shader _shader
     cdef dict state_stacks
     cdef Texture default_texture
         ^
 ------------------------------------------------------------

 E:\Projects\Arkius\.env\lib\site-packages\kivy\graphics\instructions.pxd:108:9: 'Texture' is not a type identifier

 Error compiling Cython file:
 ------------------------------------------------------------
 ...
     cdef dict bind_texture
     cdef int _use_parent_projection
     cdef int _use_parent_modelview
     cdef int _use_parent_frag_modelview

     cdef void set_texture(self, int index, Texture texture)
                                           ^
 ------------------------------------------------------------

 E:\Projects\Arkius\.env\lib\site-packages\kivy\graphics\instructions.pxd:114:43: 'Texture' is not a type identifier
 Traceback (most recent call last):
   File "setup.py", line 184, in <module>
     extensions, core_modules)
   File "setup.py", line 164, in build_extensions_for_modules_cython
     return cythonize(ext_list, compiler_directives={'language_level': '3'})
   File "E:\Projects\Arkius\.env\lib\site-packages\Cython\Build\Dependencies.py", line 1096, in cythonize
     cythonize_one(*args)
   File "E:\Projects\Arkius\.env\lib\site-packages\Cython\Build\Dependencies.py", line 1219, in cythonize_one
     raise CompileError(None, pyx_file)
 Cython.Compiler.Errors.CompileError: kivent_core/managers/resource_managers.pyx```

**Comment by Whatnoww** [comment]
Same issue.

**Comment by DavidLP** [comment]
For me too :-(

**Comment by DavidLP** [comment]
You have to compile `kivy` from source, to be able to compile `kivent`. See #283.

**Comment by Whatnoww** [comment]
@DavidLP I'll try to do that.

**Comment by stasalcatraz** [comment]
I've build kivy from master branch like in [#283](https://github.com/kivy/kivent/issues/283), but got the same error
