### ISSUE TITLE
Kivent on Raspberry Pi 2

### ISSUE THREAD

**Issue by zeth** [kivy/kivent#92]
Hello, I am trying to use kivent on the Raspberry Pi 2 and I get an error about "undefined symbol: glVertexAttribPointer" when I try to run the examples.

I did get the kivy examples to work. Full log follows. Thanks for your time.

```python
pi@raspberrypi ~/kiventproject/kivent/examples/1_empty_kivent_app $ python main.py 
[INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_15-09-25_21.txt
[INFO   ] [Kivy        ] v1.9.1-dev
[INFO   ] [Python      ] v2.7.3 (default, Mar 18 2014, 05:13:23) 
[GCC 4.6.3]
[INFO   ] [Factory     ] 177 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_pygame, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [GL          ] OpenGL version <OpenGL ES 2.0>
[INFO   ] [GL          ] OpenGL vendor <Broadcom>
[INFO   ] [GL          ] OpenGL renderer <VideoCore IV HW>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <OpenGL ES GLSL ES 1.00>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Shader      ] fragment shader: <Compiled>
[INFO   ] [Shader      ] vertex shader: <Compiled>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "main.py", line 4, in <module>
     import kivent_core
   File "/usr/local/lib/python2.7/dist-packages/kivent_core/__init__.py", line 3, in <module>
     from . import rendering
   File "/usr/local/lib/python2.7/dist-packages/kivent_core/rendering/__init__.py", line 1, in <module>
     from . import vertex_format
 ImportError: /usr/local/lib/python2.7/dist-packages/kivent_core/rendering/vertex_format.so: undefined symbol: glVertexAttribPointer
```

**Comment by zeth** [comment]
BTW obvious note:
The Kivy source code never uses the word raspberry pi, it is uses the word rpi, e.g. here: 
https://github.com/kivy/kivy/blob/master/kivy/config.py#L291
